#ifndef __CONFIG_H
#define __CONFIG_H

#include "generic.h"

#define ADC_RUN_TRIGGER_FREQ (US_RUN_FREQ * 4)
#define US_RUN_FREQ 40000
#define TIM3_CH1_COMPARE 1
#define TIM1_RUN_PERIOD (TIM1_CLOCK_FREQ/US_RUN_FREQ)
#define TIM3_RUN_PERIOD (TIM3_CLOCK_FREQ/ADC_RUN_TRIGGER_FREQ)
#define TIM1_RUN_RELOAD (TIM1_RUN_PERIOD-1)
#define TIM3_RUN_RELOAD (TIM3_RUN_PERIOD-1)
#define TIM3_CLOCK_FREQ 64000000
#define TIM1_CLOCK_FREQ 64000000
#define ADC_NUM_OF_SAMPLES 80
#define CHA_A_Pin GPIO_PIN_0
#define CHA_A_GPIO_Port GPIOA
#define CHA_B_Pin GPIO_PIN_1
#define CHA_B_GPIO_Port GPIOA
#define CHA_C_Pin GPIO_PIN_2
#define CHA_C_GPIO_Port GPIOA
#define PULSE_N_Pin GPIO_PIN_7
#define PULSE_N_GPIO_Port GPIOA
#define PULSE_Pin GPIO_PIN_8
#define PULSE_GPIO_Port GPIOA
#define PWM_Y_Pin GPIO_PIN_9
#define PWM_Y_GPIO_Port GPIOA
#define PWM_X_Pin GPIO_PIN_10
#define PWM_X_GPIO_Port GPIOA

// Adjustable parameters.
#define DEFAULT_PWM_RANGE 25.0f

// Vdda voltage.
#define VDDA_VOLTAGE_IN_MV 3300.0f

// Calibration state configuration.
#define CALIBRATION_POLY_DEGREE 3
#define CALIBRATION_PERIOD_START 1480
#define CALIBRATION_PERIOD_STOP 1720
#define CALIBRATION_PERIOD_STEP 4 
#define CALIBRATION_SAMPLE_POINTS \
    (((CALIBRATION_PERIOD_STOP - CALIBRATION_PERIOD_START) / CALIBRATION_PERIOD_STEP) + 1)

#define CORRELATION_SCORE_NORM_WEIGHT 0.90f
#define CORRELATION_SCORE_PHASE_WEIGHT 0.10f
#define CORRELATION_INTERPOLATION_NUMBER 10

// Starting state configuration.
#define SEARCHING_PERIOD_START 1540
#define SEARCHING_PERIOD_STOP 1660
#define SEARCHING_PERIOD_STEP 4
#define SEARCHING_SAMPLE_POINTS \
    (((SEARCHING_PERIOD_STOP - SEARCHING_PERIOD_START) / SEARCHING_PERIOD_STEP) + 1)

#define RUN_TRACKING_START_IDX \
    (((TIM1_RUN_PERIOD - SEARCHING_PERIOD_START) / SEARCHING_PERIOD_STEP))

#define FLASH_CODE 0x19897044
#endif