#ifndef __CONFIG_H
#define __CONFIG_H

#include "generic.h"

#define ADC_RUN_TRIGGER_FREQ (US_RUN_FREQ * 4)
#define US_RUN_FREQ 40000
#define TIM3_CH1_COMPARE 1
#define TIM1_RUN_PERIOD (TIM1_CLOCK_FREQ/US_RUN_FREQ)
#define TIM3_RUN_PERIOD (TIM3_CLOCK_FREQ/ADC_RUN_TRIGGER_FREQ)
#define TIM1_RUN_RELOAD (TIM1_RUN_PERIOD-1)
#define TIM3_RUN_RELOAD (TIM3_RUN_PERIOD-1)
#define TIM3_CLOCK_FREQ 64000000
#define TIM1_CLOCK_FREQ 64000000
#define ADC_NUM_OF_SAMPLES 80
#define CHA_A_Pin GPIO_PIN_0
#define CHA_A_GPIO_Port GPIOA
#define CHA_B_Pin GPIO_PIN_1
#define CHA_B_GPIO_Port GPIOA
#define CHA_C_Pin GPIO_PIN_2
#define CHA_C_GPIO_Port GPIOA
#define PULSE_N_Pin GPIO_PIN_7
#define PULSE_N_GPIO_Port GPIOA
#define PULSE_Pin GPIO_PIN_8
#define PULSE_GPIO_Port GPIOA
#define PWM_Y_Pin GPIO_PIN_9
#define PWM_Y_GPIO_Port GPIOA
#define PWM_X_Pin GPIO_PIN_10
#define PWM_X_GPIO_Port GPIOA

// Adjustable parameters.
#define DEFAULT_PWM_RANGE 25.0f

// Vdda voltage.
#define VDDA_VOLTAGE_IN_MV 3300.0f

// Response function sampling. In units of TIM1 tick.
#define RESP_FUNC_SAMPLE_POINTS 41
#define RESP_FUNC_SAMPLING_INTERVAL 4
#define RESP_FUNC_PERIOD_STOP 1540
#define RESP_FUNC_PERIOD_START (RESP_FUNC_PERIOD_STOP - ((RESP_FUNC_SAMPLE_POINTS - 1) * RESP_FUNC_SAMPLING_INTERVAL))

#define NUM_OF_SEARCH_SCALES 200

#define CORRELATION_SCORE_NORM_WEIGHT 0.75f
#define CORRELATION_SCORE_PHASE_WEIGHT 0.25f
#define CORRELATION_WINDOWED_SAMPLES 21
#define CORRELATION_INTERVAL_SLICING 8

#define TRANSDUCER_CAPACITANCE 2.6E-9
#define TRANSDUCER_RESISTANCE 1.8E3

#define FLOW_ROOM_TEMPERATURE 20.0f

#define RUN_TRACKING_START_IDX \
    (((TIM1_RUN_PERIOD - SEARCHING_PERIOD_START) / PERIOD_STEP))

#define FLASH_CODE 0x19897044
#endif